### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by phpgao** [Kxrr/nutstore-cli#2]
首先赞一个，命令行工具很好用，但是在通过对比dropbox的工具后，觉得还有一些改进的地方，比较有利于自动化，不知可否参考一下？

1. dropbox有一个初始化流程，会在当前用户home下建立一个.dropbox文件，里面记录了cmd需要的参数，比如key和email
2. 之后命令行只需要直接执行xxx upload loacl_path remote_path 即可

**Comment by Kxrr** [comment]
感谢你的提议，这两个特性确实非常实用，我会抽空加上。

**Comment by Kxrr** [comment]
这两个特性在 `v0.4.1` 中已经实现。

**Comment by phpgao** [comment]
⚘️ 鲜花送上
